name: test
on: [issue_comment]
jobs:
  react-to-comment:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      run: |
        pip install PyGithub
        pip install git+https://github.com/boegel/github-actions.git
    - name: react to comment
      shell: python
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        import os, pprint
        
        # collect event data
        from actions import get_event_data
        event_data = get_event_data()
        pprint.pprint(event_data)
        
        # print comment body
        print(event_data['comment']['body'])
        
        # reply to comment
        token = os.environ['GITHUB_TOKEN']
        from github import Github
        g = Github(token)
        
        repo_owner = event_data['repository']['owner']['login']
        repo_name = event_data['repository']['name']
        repo = g.get_repo(repo_owner + '/' + repo_name)
        
        issue = repo.get_issue(number=event_data['issue']['number'])
        issue.create_comment("Thank you for your comment @%s!" % event_data['sender']['login'])
