name: CI

on: [issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: print event data
      shell: python
      run: |
        import json, os, pprint
        event_path = os.environ['GITHUB_EVENT_PATH']
        event_data = json.load(open(event_path))
        pprint.pprint(event_data)
